name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:     "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"  # GitHub token
          armbian_release:   "bookworm"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "rockpi-4bplus"                   # build target
          
